### ISSUE TITLE
Redirect to index.php again

### ISSUE THREAD

**Issue by troke12** [urls/url-shortener#11]
I just put your code in my website and configuration but the shortlink redirect to index.php 
http://link.troke.id/gila
Maybe problem at .htaccess or what?

**Comment by amarlearning** [comment]
> [http://link.troke.id/gila](http://link.troke.id/gila)
@troke12 This link is not working, please mention the correct link.

**Comment by troke12** [comment]
i'm sorry it's solved, i changed to another services url shorterner to rebrandly

**Comment by troke12** [comment]
it's been a year and noone solve it
