### ISSUE TITLE
no option for memorable url

### ISSUE THREAD

**Issue by amarlearning** [urls/url-shortener#4]

**Comment by mangroud** [comment]
Hi @amarlearning 

can you give me more details about what do you need on this issue please? Do you want a function to display the short url when the user types an existent url? 

Thanks

**Comment by amarlearning** [comment]
Hi @mangroud  

whenever a user shorten a url, php script generate a random code for the url like this  [ 5yc1u ], then the end shorten url will be : http://urls.ml/5yc1u

But i want user to input that random code if he wants.

For example if a user inputs a random code : [ myresume ], then the generated url will be : http://urls.ml/myresume

Let me know if you have any other doubt! :+1:

**Comment by amarlearning** [comment]
@mangroud your update's working fine. closing this issue now.
