### ISSUE TITLE
web server needed to make urls.ml run 

### ISSUE THREAD

**Issue by amarlearning** [urls/url-shortener#5]

**Comment by mangroud** [comment]
Please let me know if this is what you need

**Comment by amarlearning** [comment]
@mangroud  thanks for adding the .htaccess file. But i actually need a web server [hosting space], to host this application.

**Comment by mangroud** [comment]
I can host your project on my VPS if you want. 
Send me an email and I will provide you the DNS for the domain 👍

**Comment by amarlearning** [comment]
@mangroud send you an email. Please check!

**Comment by 0xcrypto** [comment]
You can use openshift. They provide free paas hosting.

**Comment by markwalet** [comment]
I think this issue can be closed.

**Comment by amarlearning** [comment]
@markwalet I still didn't get any server!

**Comment by markwalet** [comment]
Why is needing a web server an issue in code?
Something like this should be putted in the readme.
And also, someone else already sent you an email with some vps details. That didn't work out?

**Comment by amarlearning** [comment]
@markwalet he didn't sent me any email!

**Comment by swapsha96** [comment]
Can someone tell me where is urls.ml file?

**Comment by swapsha96** [comment]
Can someone tell me where is urls.ml file?

**Comment by amarlearning** [comment]
@swapsha96 URLs.ml is a domain not a file!

**Comment by swapsha96** [comment]
Oh I'm sorry. I read it wrong. I'm a PHP/mySQL developer. Please tell me what do I have to do. I'm ready to take this project.

**Comment by mayank** [comment]
@amarlearning you can use [heroku.com][1] for PHP + PostgreSQL for free.

[1]: https://heroku.com

**Comment by amarlearning** [comment]
@mayank Thanks for bringing Heroku to my notice.
But as you know Heroku offers subdomain for your application hosting.
And I think for a URL shortener a subdomain might not look good!

**Comment by mayank** [comment]
buy a domain and attach it to heroku

**Comment by amarlearning** [comment]
@mayank ok! Thanks :wink:
